[package]
name = "sleipnir"
version = "0.2.2"
edition = "2021"
license = "MIT/Apache-2.0"
description = "Memory safe font operations for Google Fonts."
repository = "https://github.com/googlefonts/sleipnir"
readme = "README.md"
categories = ["text-processing", "parsing", "graphics"]

[features]

[dependencies]
kurbo = "0.11.0"
skrifa = "0.19.1"

smol_str = "0.2.1"
smallvec = "1.13"
thiserror = "1.0.57"
rayon = "1.8.0"

[dev-dependencies]
regex = "1.10.4"
pretty_assertions="1.4"
write-fonts = "0.27.0"

